### ISSUE TITLE
App creation fails if yarn isn't installed, even if yarn isn't selected or used for running create-relay-app

### ISSUE THREAD

**Issue by expesh** [tobias-tengler/create-relay-app#11] opened 2022-09-07 20:45 UTC
Here's the error log:
```
Command "npm install --save-exact --save-dev relay-compiler@latest @types/react-relay@latest @types/relay-runtime@latest babel-plugin-relay@latest vite-plugin-relay@https://github.com/tobias-tengler/vite-plugin-relay#tte/fix-plugin" failed

npm ERR! code 127
npm ERR! git dep preparation failed
npm ERR! command /home/dev/.nvm/versions/node/v16.16.0/bin/node /home/dev/.nvm/versions/node/v16.16.0/lib/node_modules/npm/bin/npm-cli.js install --force --cache=/home/dev/.npm --prefer-offline=false --prefer-online=false --offline=false --no-progress --no-save --no-audit --include=dev --include=peer --include=optional --no-package-lock-only --no-dry-run
npm ERR! > vite-plugin-relay@2.0.0 prepare
npm ERR! > husky install && yarn build
npm ERR! npm WARN using --force Recommended protections disabled.
npm ERR! fatal: not a git repository (or any of the parent directories): .git
npm ERR! sh: line 1: yarn: command not found
npm ERR! npm ERR! code 127
npm ERR! npm ERR! path /home/dev/.npm/_cacache/tmp/git-cloneUKSqXM
npm ERR! npm ERR! command failed
npm ERR! npm ERR! command sh -c husky install && yarn build
npm ERR! 
npm ERR! npm ERR! A complete log of this run can be found in:
npm ERR! npm ERR!     /home/dev/.npm/_logs/2022-09-07T18_54_35_818Z-debug-0.log

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/dev/.npm/_logs/2022-09-07T18_54_31_413Z-debug-0.log
```

Seems like probably the command `sh -c husky install && yarn build` is making the whole thing fail.

Looking at the README, the first step is only using yarn:

> 1. Scaffold a new project using the toolchain of your choice (as long as [it's supported](#supported-toolchains))
>    - Next.js: `yarn create next-app --typescript`
>    - Vite.js: `yarn create vite --template react-ts`
>    - Create React App: `yarn create react-app <new-project-directory> --template typescript`

But the 3rd steps shows that any package manager can be used:

> 3. Run the script inside of the scaffolded directory:
> 
> ```bash
> npm/yarn/pnpm create @tobiastengler/relay-app@latest
> ```

I think there maybe should be a clearer note in the docs that a yarn installation is also required for running the command in the 3rd step.

**Comment by tobias-tengler** [comment] 2022-09-07 21:22
Thanks for reporting!

Looking at the log ouput this seems to come from the `vite-plugin-relay` package.
You can see the prepare script here: https://github.com/oscartbeaumont/vite-plugin-relay/blob/042c343c91527ff9f4946ad5d665387b91cabef2/package.json#L32

You should get the same error just trying to install that package using `npm install vite-plugin-relay` (haven't confirmed).

If this is true you should raise an issue with the repo of vite-plugin-relay. But the owner of the package is pretty unresponsive. I have sent a PR that adds Vite 3 support, but it hasn't been reviewed in almost a month now...

I'm closing this issue since there's nothing I can do about it.

If what I said above is in fact not true, feel free to re-open :)

**Comment by tobias-tengler** [comment] 2022-09-07 21:30
Okay this seems to actually be my fault. Since I'm installing the vite-plugin-relay package from the branch where I added Vite 3 support, the package is built on your system, which probably causes this issue.

I'll remove the install from branch and instead provide guidance on how to add Vite 3 support manually until my PR is merged. But now it's 💤 time for me, so I'll try to get a fix out tomorrow :)

**Comment by tobias-tengler** [comment] 2022-09-08 08:45
I just published v0.0.6, which should address this issue.

You can simply re-run the script:

```
npm create @tobiastengler/relay-app@latest`
```

and the error should no longer happen.

Now you have to add the fixed Vite plugin to your code manually, which is detailed here: https://github.com/tobias-tengler/create-relay-app/blob/main/docs/vite-plugin-setup.md (It will also be shown in the console)

Let me know if you have any other issues :)

**Closed by tobias-tengler** 2022-09-08 08:45 UTC

**Comment by expesh** [comment] 2022-09-08 16:41
Thanks. It might be worth adding to the docs that you also need to modify `tsconfig.node.json` to add the `lib` field to something es6+. Even though you already have this note:

> If you are using an ECMAScript standard below ES6 you need to replace the src.includes("graphql") with src.indexOf("graphql") !== -1

Since the default is having `lib` unset, I think having an explicit note of the change would be good since it's a change from the bootstrapped app that the tool creates (and falls into the vite plugin setup imo).

**Comment by tobias-tengler** [comment] 2022-09-08 17:31
Yep, that's true. I'll just change the code to match the default and remove the note :)

**Comment by tobias-tengler** [comment] 2022-09-10 15:12
My `vite-plugin-relay` PR was merged today and I published version 0.0.7 of this package which now will install the `vite-plugin-relay` package properly. So no more workaround is required. :)

**Comment by Presipope** [comment] 2023-04-26 02:54
I'm unsure if I'm wrongfully drudging this up but I've been having trouble getting the script this to work on a new Vite.js project. 

I installed Vite.js, and then ran the standard npm script npm create @tobiastengler/relay-app and it fails after "Add RelayEnvironmentProvider". It doesn't seem to be installing the "vite-plugin-relay" in the package.json and from that point on my attempts to fix the problems hasn't worked. Curious if you have a similar issue with a fresh install.

**Comment by tobias-tengler** [comment] 2023-04-26 05:24
If you are creating a new Vite.js App using the Vite CLI and run this package afterwards, everything should work. This is also covered by an integration test on our side. 
Can you please
- tell me how you setup your Vite.js project
- send me a copy of the log output of the failed create-relay-app command
- attach your current project files as a .zip for me to investigate

**Comment by Presipope** [comment] 2023-04-26 20:24
Everything worked! In my particular scenario on the existing project it added in "babel-plugin-relay": "^15.0.0" as well as adjusting react-relay/relay-runtime to be version "^15.0.0". 

Thanks for the fast response @tobias-tengler :)
